services:
  discord-bot:
    build: ./discord-bot
    entrypoint: |
      bash -c 'nodemon --exec ruby bot.rb'
    volumes:
      - ./discord-bot:/bot
      
    environment:
      - DISCORD_BOT_TOKEN
